Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2018-11, with the labels that each got.

#29 add Ben as top level approver
  OWNERS
Labels: approved, lgtm, size/XS

#28 Add Build CRD to Manifests
  manifests/0000_21_cluster-openshift-controller-manager-operator_06_build.crd.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_07_deployment.yaml
Labels: approved, lgtm, size/S

#26 observe internal registry hostname
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L

#31 use pullalways for the operator image
  manifests/0000_21_cluster-openshift-controller-manager-operator_07_deployment.yaml
Labels: approved, lgtm, size/XS

#34 move to operator specific namespace
  manifests/0000_21_cluster-openshift-controller-manager-operator_00_namespace.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_02_configmap.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_03_builder-deployer-config.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_04_roles.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_07_deployment.yaml
  pkg/operator/starter.go
Labels: approved, lgtm, size/S

#27 Observe Cluster BuildController config
  .gitignore
  manifests/0000_21_cluster-openshift-controller-manager-operator_01_config.crd.yaml
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
Labels: approved, lgtm, size/L

#36 add e2e test for cluster-manager-operator
  Makefile
  test/e2e/cluster_openshift_controller_manager_operator_test.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/L

#39 fix informers for operator namespace
  pkg/operator/observe_config.go
  pkg/operator/operator.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/S
