Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2018-10, with the labels that each got.

#9 Add soltysh to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#8 update manifest filenames to conform to expected CVO update payload format
  manifests/0000_21_cluster-openshift-controller-manager-operator_00_namespace.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_01_config.crd.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_02_config.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_03_configmap.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_04_roles.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_06_deployment.yaml
Labels: approved, lgtm, size/XS

#12 tolerate any taint
  bindata/v3.11.0/openshift-controller-manager/ds.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_06_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#13 remove operator config from payload
  bindata/v3.11.0/openshift-controller-manager/operator-config.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#15 ensure operator config exists on start
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#16 bump
  glide.lock
  pkg/operator/operator.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  vendor/github.com/openshift/api/authorization/OWNERS
  vendor/github.com/openshift/api/oauth/OWNERS
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/OWNERS
  vendor/github.com/openshift/api/user/OWNERS
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
Labels: approved, lgtm, size/L

#18 add image references
  manifests/0000_21_cluster-openshift-controller-manager-operator_06_deployment.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#20 report status to the CVO
  glide.lock
  pkg/operator/starter.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/library-go/.travis.yml
  vendor/github.com/openshift/library-go/glide.lock
  vendor/github.com/openshift/library-go/hack/verify-golint.sh
  vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
Labels: approved, lgtm, size/L

#21 fix ClusterOperator typos
  glide.lock
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
Labels: approved, lgtm, size/M

#22 add configmap for builder, deployer image data
  manifests/0000_21_cluster-openshift-controller-manager-operator_02_configmap.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_03_builder-deployer-config.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#24 complete config observer
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  pkg/operator/operator.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L
