Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2018-09, with the labels that each got.

#2 Add tnozicka
  OWNERS
Labels: size/XS

#3 CI fixes
  .gitignore
  Dockerfile
  Makefile
  cluster-openshift-controller-manager-operator.spec
  hack/build-cross.sh
  hack/build-go.sh
  hack/build-images.sh
  hack/build-rpms.sh
  hack/cherry-pick.sh
  hack/import-restrictions.json
  hack/lib/build/images.sh
  hack/move-upstream.sh
  hack/push-release.sh
  hack/test-go.sh
  hack/update-codegen.sh
  hack/update-generated-bindata.sh
  hack/verify-codegen.sh
  hack/verify-generated-bindata.sh
  hack/verify-gofmt.sh
  hack/verify-govet.sh
  hack/verify-imports.sh
  hack/verify-upstream-commits.sh
  pkg/operator/start_test.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XXL

#6 update to flat updatepayload structure
  Dockerfile
  bindata/v3.11.0/openshift-controller-manager/cm.yaml
  bindata/v3.11.0/openshift-controller-manager/defaultconfig.yaml
  bindata/v3.11.0/openshift-controller-manager/deployment.yaml
  bindata/v3.11.0/openshift-controller-manager/informer-clusterrole.yaml
  bindata/v3.11.0/openshift-controller-manager/informer-clusterrolebinding.yaml
  bindata/v3.11.0/openshift-controller-manager/leader-role.yaml
  bindata/v3.11.0/openshift-controller-manager/leader-rolebinding.yaml
  bindata/v3.11.0/openshift-controller-manager/ns.yaml
  bindata/v3.11.0/openshift-controller-manager/public-info-role.yaml
  bindata/v3.11.0/openshift-controller-manager/public-info-rolebinding.yaml
  bindata/v3.11.0/openshift-controller-manager/public-info.yaml
  bindata/v3.11.0/openshift-controller-manager/sa.yaml
  bindata/v3.11.0/openshift-controller-manager/separate-sa-role.yaml
  bindata/v3.11.0/openshift-controller-manager/separate-sa-rolebinding.yaml
  bindata/v3.11.0/openshift-controller-manager/svc.yaml
  hack/update-generated-bindata.sh
  manifests/00_clusteropenshiftcontrollermanageroperator_00_namespace.yaml
  manifests/00_clusteropenshiftcontrollermanageroperator_01_config.crd.yaml
  manifests/00_clusteropenshiftcontrollermanageroperator_02_config.yaml
  manifests/00_clusteropenshiftcontrollermanageroperator_03_configmap.yaml
  manifests/00_clusteropenshiftcontrollermanageroperator_04_roles.yaml
  manifests/00_clusteropenshiftcontrollermanageroperator_05_serviceaccount.yaml
  manifests/00_clusteropenshiftcontrollermanageroperator_06_deployment.yaml
  manifests/install/operator.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L
