Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2019-02, with the labels that each got.

#67 build config crd has moved to the cluster-config-operator
  manifests/0000_63_openshift-controller-manager-operator_08_build.crd.yaml
Labels: approved, lgtm, size/S

#68 drop operator suffix from clusteroperator object
  manifests/0000_63_openshift-controller-manager-operator_10_clusteroperator.yaml
  pkg/operator/starter.go
  test/framework/conditionhelper.go
Labels: approved, lgtm, size/XS

#71 ensure serving cert update triggers controller rollout
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
Labels: approved, lgtm, size/S

#72 rename controller operator resource instance from 'instance' to 'cluster'
  bindata/v3.11.0/openshift-controller-manager/operator-config.yaml
  pkg/operator/generic_client.go
  pkg/operator/operator.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
  test/e2e/cluster_openshift_controller_manager_operator_test.go
Labels: approved, lgtm, size/S

#73 no need for post-startup cache sync checks
  pkg/operator/configobservation/builds/observe_builds.go
  pkg/operator/configobservation/builds/observe_builds_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/deployimages/observe_deployimages.go
  pkg/operator/configobservation/deployimages/observe_deployimages_test.go
  pkg/operator/configobservation/images/observe_images.go
  pkg/operator/configobservation/images/observe_images_test.go
  pkg/operator/configobservation/interfaces.go
Labels: approved, lgtm, size/M

#76 add object refs for must gather dump
  Makefile
  pkg/operator/configobservation/deployimages/observe_deployimages.go
  pkg/operator/configobservation/deployimages/observe_deployimages_test.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/util/consts.go
Labels: approved, lgtm, size/M

#78 bump(*): pick up https://github.com/openshift/library-go/pull/284
  glide.lock
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/pkg/assets/template.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_networking_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
Labels: approved, lgtm, size/XXL

#80 Drop etcd metrics
  manifests/0000_90_openshift-controller-manager-operator_02_servicemonitor.yaml
  manifests/0000_90_openshift-controller-manager-operator_03_operand-servicemonitor.yaml
Labels: approved, lgtm, size/S
