Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2019-10, with the labels that each got.

#120 rbac for lock for addn of cluster-policy-controller 4.2->4.3
  bindata/v3.11.0/openshift-controller-manager/cluster-policy-controller-leader-role.yaml
  bindata/v3.11.0/openshift-controller-manager/cluster-policy-controller-leader-rolebinding.yaml
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#121 update README and `make images`
  Makefile
  README.md
Labels: approved, lgtm, size/S

#125 rm role/binding for cluster-policy-controller leader lock, goes in kcm-o
  bindata/v3.11.0/openshift-controller-manager/cluster-policy-controller-leader-role.yaml
  bindata/v3.11.0/openshift-controller-manager/cluster-policy-controller-leader-rolebinding.yaml
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L

#128 Add soltysh to approvers
  OWNERS
Labels: approved, lgtm, size/XS
