Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2019-01, with the labels that each got.

#49 set available, progressing statuses on operator/clusteroperator status
  manifests/0000_21_cluster-openshift-controller-manager-operator_08_clusteroperator.yaml
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/testframework/clientset.go
  pkg/testframework/conditionhelper.go
  pkg/testframework/framework.go
  test/e2e/cluster_openshift_controller_manager_operator_test.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/L

#50 fix progressing condition logic
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
Labels: approved, lgtm, size/S

#47 Git Proxy Support
  glide.lock
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/openshiftcontrolplane/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/Makefile
  vendor/github.com/openshift/library-go/glide.yaml
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/testfiles/tls-expired.crt
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/testfiles/tls-multiple.crt
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/testfiles/tls.crt
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/testfiles/tls.key
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/events/eventstesting/recorder_testing.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring_test.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/manifests/prometheus-role-binding.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/manifests/prometheus-role.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/manifests/service-monitor.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XXL

#51 Use DefaultProxy for Build Git Proxy
  pkg/operator/observe_config.go
  pkg/operator/observe_config_test.go
Labels: approved, lgtm, size/M

#54 remove references to operator v1alpha1 API
  pkg/apis/openshiftcontrollermanager/v1/register.go
  pkg/testframework/conditionhelper.go
Labels: approved, lgtm, size/S

#53 remove -cluster from operator namespace and name
  manifests/0000_21_cluster-openshift-controller-manager-operator_04_roles.yaml
  manifests/0000_21_cluster-openshift-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_21_openshift-controller-manager-operator_00_namespace.yaml
  manifests/0000_21_openshift-controller-manager-operator_01_config.crd.yaml
  manifests/0000_21_openshift-controller-manager-operator_02_configmap.yaml
  manifests/0000_21_openshift-controller-manager-operator_03_builder-deployer-config.yaml
  manifests/0000_21_openshift-controller-manager-operator_04_roles.yaml
  manifests/0000_21_openshift-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_21_openshift-controller-manager-operator_06_build.crd.yaml
  manifests/0000_21_openshift-controller-manager-operator_07_deployment.yaml
  manifests/0000_21_openshift-controller-manager-operator_08_clusteroperator.yaml
  pkg/cmd/operator/cmd.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/testframework/conditionhelper.go
Labels: approved, lgtm, size/M

#57 set cpu request for pod and operator
  bindata/v3.11.0/openshift-controller-manager/ds.yaml
  manifests/0000_21_openshift-controller-manager-operator_07_deployment.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#58 explicitly list metrics port as first containerPort
  manifests/0000_21_openshift-controller-manager-operator_07_deployment.yaml
Labels: approved, lgtm, size/XS

#61 move openshift controller manager later in CVO payload
  manifests/0000_63_openshift-controller-manager-operator_00_namespace.yaml
  manifests/0000_63_openshift-controller-manager-operator_01_config.crd.yaml
  manifests/0000_63_openshift-controller-manager-operator_02_configmap.yaml
  manifests/0000_63_openshift-controller-manager-operator_03_builder-deployer-config.yaml
  manifests/0000_63_openshift-controller-manager-operator_04_roles.yaml
  manifests/0000_63_openshift-controller-manager-operator_05_serviceaccount.yaml
  manifests/0000_63_openshift-controller-manager-operator_06_build.crd.yaml
  manifests/0000_63_openshift-controller-manager-operator_07_deployment.yaml
  manifests/0000_63_openshift-controller-manager-operator_08_clusteroperator.yaml
Labels: approved, lgtm, size/XS

#59 update operator status when the operand is unmanaged
  pkg/operator/operator.go
Labels: approved, lgtm, size/M

#60 add metric scraping to controller
  OWNERS
  bindata/v3.11.0/openshift-controller-manager/servicemonitor-role.yaml
  bindata/v3.11.0/openshift-controller-manager/servicemonitor-rolebinding.yaml
  bindata/v3.11.0/openshift-controller-manager/tokenreview-clusterrole.yaml
  bindata/v3.11.0/openshift-controller-manager/tokenreview-clusterrolebinding.yaml
  manifests/0000_63_openshift-controller-manager-operator_00_namespace.yaml
  manifests/0000_63_openshift-controller-manager-operator_01_operand-namespace.yaml
  manifests/0000_63_openshift-controller-manager-operator_02_config.crd.yaml
  manifests/0000_63_openshift-controller-manager-operator_03_configmap.yaml
  manifests/0000_63_openshift-controller-manager-operator_04_metricservice.yaml
  manifests/0000_63_openshift-controller-manager-operator_05_builder-deployer-config.yaml
  manifests/0000_63_openshift-controller-manager-operator_06_roles.yaml
  manifests/0000_63_openshift-controller-manager-operator_07_serviceaccount.yaml
  manifests/0000_63_openshift-controller-manager-operator_08_build.crd.yaml
  manifests/0000_63_openshift-controller-manager-operator_09_deployment.yaml
  manifests/0000_63_openshift-controller-manager-operator_10_clusteroperator.yaml
  manifests/0000_90_openshift-controller-manager-operator_00_prometheusrole.yaml
  manifests/0000_90_openshift-controller-manager-operator_01_prometheusrolebinding.yaml
  manifests/0000_90_openshift-controller-manager-operator_02_servicemonitor.yaml
  manifests/0000_90_openshift-controller-manager-operator_03_operand-servicemonitor.yaml
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/L
