Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2019-04, with the labels that each got.

#85 Failure to upgrade
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00_test.go
Labels: approved, lgtm, size/L

#87 A little bit of clean up
  pkg/operator/generic_client.go
  pkg/operator/operator.go
  pkg/operator/starter.go
  test/e2e/cluster_openshift_controller_manager_operator_test.go
Labels: approved, lgtm, size/M

#89 Switch openshift/ocm-o to go1.11
  .travis.yml
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#91 bump dependencies
  glide.lock
  pkg/operator/operator.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  test/framework/conditionhelper.go
  vendor/github.com/go-bindata/go-bindata/_config.yml
  vendor/github.com/go-bindata/go-bindata/testdata/Makefile
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_test.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/library-go/pkg/assets/create/create_test.go
  vendor/github.com/openshift/library-go/pkg/assets/create/creater.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/github.com/spf13/cobra/.circleci/config.yml
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/args_test.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completions_test.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/cobra/cmd/golden_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/init.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_test.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs_test.go
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs_test.go
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs_test.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
Labels: approved, lgtm, size/XXL

#77 Update pod.yaml to include priorityClassName
  bindata/v3.11.0/openshift-controller-manager/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/XS

#92 Use the CVO for operator config management
  manifests/0000_63_openshift-controller-manager-operator_03_config.cr.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#93 Add node-selector annotation to namespace
  manifests/0000_63_openshift-controller-manager-operator_00_namespace.yaml
  manifests/0000_63_openshift-controller-manager-operator_01_operand-namespace.yaml
Labels: approved, lgtm, size/XS

#95 Move component to an appropriate upgrade order (generic)
  manifests/00_namespace.yaml
  manifests/01_operand-namespace.yaml
  manifests/02_config.crd.yaml
  manifests/03_config.cr.yaml
  manifests/03_configmap.yaml
  manifests/04_metricservice.yaml
  manifests/05_builder-deployer-config.yaml
  manifests/06_roles.yaml
  manifests/07_serviceaccount.yaml
  manifests/09_deployment.yaml
  manifests/10_clusteroperator.yaml
Labels: approved, lgtm, size/XS
