Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2019-08, with the labels that each got.

#112 Bug 1736812: fix apiVersion for operator config
  manifests/03_configmap.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#114 bump(*)
  glide.lock
  vendor/github.com/evanphx/json-patch/go.mod
  vendor/github.com/evanphx/json-patch/go.sum
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/evanphx/json-patch/patch_test.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/go.mod
  vendor/github.com/ghodss/yaml/go.sum
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/ghodss/yaml/yaml_go110.go
  vendor/github.com/ghodss/yaml/yaml_go110_test.go
  vendor/github.com/ghodss/yaml/yaml_test.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/bench_test.go
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/errors_test.go
  vendor/github.com/pkg/errors/example_test.go
  vendor/github.com/pkg/errors/format_test.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/pkg/errors/stack_test.go
Labels: approved, lgtm, size/XXL

#116 Bug 1719188: set library-go bits to declare we do not support unmanaged/removed; allow all other reconciliaition as part of ignoring unmanaged/removed; clean up messages around not supporting unmanaged/removed
  pkg/operator/operator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
