Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2019-05, with the labels that each got.

#96 Bug 1704874: Create ConfigMap for Registry CA
  bindata/v3.11.0/openshift-controller-manager/openshift-service-ca-cm.yaml
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#97 Fix tolerations
  manifests/09_deployment.yaml
Labels: approved, lgtm, size/S

#98 set terminationMessagePolicy to FallbackToLogsOnError
  manifests/09_deployment.yaml
Labels: approved, lgtm, size/XS

#100 Remove old values from config CR
  manifests/03_config.cr.yaml
Labels: approved, lgtm, size/XS
