Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2020-02, with the labels that each got.

#139 Bug 1804432: Fallback to logs on ocm termination
  bindata/v3.11.0/openshift-controller-manager/ds.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#140 Bug 1804434: Report "Progressing=True" during ds rollout
  bindata/v3.11.0/openshift-controller-manager/ds.yaml
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00_test.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#138 Move default config to its own path
  bindata/v3.11.0/config/defaultconfig.yaml
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm, size/M

#143 Bug 1806913: Remove run-level for OCM and operator
  manifests/00_namespace.yaml
  manifests/01_operand-namespace.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
