Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2020-07, with the labels that each got.

#160 Bug 1852249: ensure progressing is not set to false if version is missing
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#161 Bug 1854133: ensure progressing is not set to false if version is missing
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#153 Move operand namespace creation to operator rather than CVO
  bindata/v3.11.0/openshift-controller-manager/ns.yaml
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, lgtm

#163 Bug 1852964: account for nil DaemonSet returned from library-go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#162 Bug 1826183: Sync proxy CA to openshift-controller-manager
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/usercaobservation/user_ca_observation_controller.go
  pkg/operator/usercaobservation/user_ca_observation_controller_test.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_scheduler.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
