Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2022-09, with the labels that each got.

#259 OCPBUGS-722: Fix NPD when accessing rote controller spec.deployment.replicas
  bindata/v3.11.0/openshift-controller-manager/route-controller-deploy.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#262 OCPBUGS-722: handle errors during operand creation and update
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#263 fix README links
  README.md
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#257 rename operator queue to OpenshiftControllerManagerOperator
  pkg/operator/operator.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#258 switch to route-controller-manager image and use ApplyDeployment
  bindata/v3.11.0/openshift-controller-manager/route-controller-deploy.yaml
  manifests/09_deployment.yaml
  manifests/image-references
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00_test.go
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved

#265 Revert "switch to route-controller-manager image and use ApplyDeployment"
  bindata/v3.11.0/openshift-controller-manager/route-controller-deploy.yaml
  manifests/09_deployment.yaml
  manifests/image-references
  pkg/operator/operator.go
  pkg/operator/starter.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00_test.go
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm
