Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2022-07, with the labels that each got.

#247 Bug 2110617: Add namespace and RBAC needed for ingress-to-route
  bindata/v3.11.0/openshift-controller-manager/leader-ingress-to-route-controller-role.yaml
  bindata/v3.11.0/openshift-controller-manager/leader-ingress-to-route-controller-rolebinding.yaml
  bindata/v3.11.0/openshift-controller-manager/route-controller-ns.yaml
  pkg/operator/starter.go
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#248 Bug 2110629: Set openshift.io/run-level to nil in openshift-controller-manager namespace
  bindata/v3.11.0/openshift-controller-manager/ns.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#249 Bug 2110715: Set openshift.io/run-level to nil in openshift-controller-manager namespace
  bindata/v3.11.0/openshift-controller-manager/ns.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, staff-eng-approved

#253 Adding leader election leases permissions for openshift-controller-manager-sa
  bindata/v3.11.0/openshift-controller-manager/separate-sa-role.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved
