Repository openshift/cluster-openshift-controller-manager-operator, pull requests merged in 2024-05, with the labels that each got.

#336 AUTH-482: set required-scc for openshift workloads
  bindata/assets/openshift-controller-manager/deploy.yaml
  bindata/assets/openshift-controller-manager/route-controller-manager-deploy.yaml
  manifests/09_deployment.yaml
Labels: lgtm, approved, jira/valid-reference

#347 OCPBUGS-34054: lots of churn during image registry managed/removed transition
  pkg/operator/internalimageregistry/cleanup_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#346 OCPBUGS-34077: Always Disable Default Rolebindings Controller
  pkg/operator/configobservation/controllers/observe_controllers.go
  pkg/operator/configobservation/controllers/observe_controllers_test.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00.go
  pkg/operator/sync_openshiftcontrollermanager_v311_00_test.go
Labels: lgtm, approved, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/valid-reference

#351 OCPBUGS-34395: Move `cluster` Build CR to runlevel 10 to match CRD
  empty-resources/0000_10_openshift-controller-manager-operator_02_build_cr.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference
